# Generated by Django 5.2.3 on 2025-06-13 14:17

import django.db.models.deletion
import django.utils.timezone
import tm_meeting.constants.meeting
import tm_utils.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tm_club", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TMMeeting",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(default="", max_length=255)),
                ("date", models.DateTimeField(default=None, null=True)),
                ("address", models.CharField(default="", max_length=255)),
                ("number", tm_utils.models.fields.PositiveTinyIntegerField()),
                (
                    "club",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tm_club.tmclub",
                    ),
                ),
            ],
            options={
                "db_table": "tm_meeting",
            },
        ),
        migrations.CreateModel(
            name="TMSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    tm_utils.models.fields.PositiveTinyIntegerField(
                        default=tm_meeting.constants.meeting.SessionType["UNKNOWN"]
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tm_meeting.tmmeeting",
                    ),
                ),
            ],
            options={
                "db_table": "tm_session",
            },
        ),
        migrations.CreateModel(
            name="TMSpeech",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    tm_utils.models.fields.PositiveTinyIntegerField(
                        default=tm_meeting.constants.meeting.MeetingRole["UNKNOWN"]
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speeches",
                        to="tm_meeting.tmsession",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speeches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tm_speech",
            },
        ),
        migrations.AddIndex(
            model_name="tmmeeting",
            index=models.Index(fields=["club"], name="idx_meeting_club"),
        ),
        migrations.AddIndex(
            model_name="tmsession",
            index=models.Index(fields=["meeting"], name="idx_session_meeting"),
        ),
        migrations.AddIndex(
            model_name="tmspeech",
            index=models.Index(fields=["session"], name="idx_speech_session"),
        ),
        migrations.AddIndex(
            model_name="tmspeech",
            index=models.Index(fields=["speaker"], name="idx_speech_speaker"),
        ),
    ]
