# Generated by Django 4.2.21 on 2025-05-23 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tm_user.constants.toastmaster
import tm_utils.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDivision',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'tm_division',
            },
        ),
        migrations.CreateModel(
            name='TMClub',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='tm_user.tmdivision')),
            ],
            options={
                'db_table': 'tm_club',
            },
        ),
        migrations.CreateModel(
            name='TMToastMaster',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(default='', max_length=64)),
                ('level', tm_utils.models.fields.PositiveTinyIntegerField(default=tm_user.constants.toastmaster.Level['UNKNOWN'])),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toastmasters', to='tm_user.tmclub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tm_toastmaster',
                'indexes': [models.Index(fields=['user'], name='idx_toastmaster'), models.Index(fields=['club'], name='idx_toastmaster_club')],
            },
        ),
        migrations.CreateModel(
            name='TMGuest',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(default='', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tm_guest',
                'indexes': [models.Index(fields=['user'], name='idx_guest')],
            },
        ),
    ]
