# Generated by Django 5.2.3 on 2025-06-13 14:17

import django.db.models.deletion
import django.utils.timezone
import tm_utils.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tm_user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TMRegisterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("token", models.CharField(max_length=100, unique=True)),
                ("verify_code", models.CharField(max_length=6)),
                ("expired_at", models.DateTimeField()),
                ("token_expired_at", models.DateTimeField()),
                (
                    "verification_type",
                    tm_utils.models.fields.PositiveTinyIntegerField(default=1),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tm_register_form",
                "indexes": [
                    models.Index(fields=["token"], name="idx_register_form_token"),
                    models.Index(fields=["user"], name="idx_register_form_user"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TMUserAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("token", models.CharField(max_length=100, unique=True)),
                ("verify_code", models.CharField(max_length=6)),
                ("expired_at", models.DateTimeField()),
                ("token_expired_at", models.DateTimeField()),
                (
                    "verification_type",
                    tm_utils.models.fields.PositiveTinyIntegerField(default=1),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tm_user_auth",
                "indexes": [
                    models.Index(fields=["token"], name="idx_user_auth_token"),
                    models.Index(fields=["user"], name="idx_user_auth_user"),
                ],
            },
        ),
    ]
